### ISSUE TITLE
Error when returning the films of Sir Peter Robert Jackson

### ISSUE THREAD

**Issue by colmose** [daradermody/OverDB#67]
https://overdb.vercel.app/person/108

![image](https://github.com/daradermody/OverDB/assets/8244036/8b760a72-b0eb-4363-95a7-a965cd69c3cf)

**Comment by daradermody** [comment]
Note to self: An item with ID `1173608` shows up in Peter Jackson's list of movie credits, but is actually [a _collection_](https://www.themoviedb.org/collection/1173608-the-making-of-the-lord-of-the-rings-collection) rather than a _movie_, so can't actually be fetched using the `/movie/<id>` endpoint. Need to filter out collections from the credits somehow.
